### ISSUE TITLE
IEventDispatcher issue on 27

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/collectives#828]
Using the latest release on my 27 instance caused the following log entry:

We cannot just pass the IEventDispatcher here for Nextcloud <28, so we may need a fallback to pass the SymfonyDispatcher on older releases.

I can check this next week.

```
{
  "reqId": "YiBHLTQHe1Pao8XpFaFQ",
  "level": 3,
  "time": "2023-08-11T14:15:39+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job (class: OCA\\Collectives\\BackgroundJob\\ExpirePageVersions, arguments: )",
  "userAgent": "--",
  "version": "27.1.0.0",
  "exception": {
    "Exception": "TypeError",
    "Message": "OC\\User\\User::__construct(): Argument #3 ($dispatcher) must be of type Symfony\\Component\\EventDispatcher\\EventDispatcherInterface, OC\\EventDispatcher\\EventDispatcher given, called in /var/www/nextcloud/apps-extra/collectives/lib/Versions/CollectiveVersionsExpireManager.php on line 121",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps-extra/collectives/lib/Versions/CollectiveVersionsExpireManager.php",
        "line": 121,
        "function": "__construct",
        "class": "OC\\User\\User",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps-extra/collectives/lib/Versions/CollectiveVersionsExpireManager.php",
        "line": 96,
        "function": "expireFolder",
        "class": "OCA\\Collectives\\Versions\\CollectiveVersionsExpireManager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps-extra/collectives/lib/BackgroundJob/ExpirePageVersions.php",
        "line": 35,
        "function": "expireAll",
        "class": "OCA\\Collectives\\Versions\\CollectiveVersionsExpireManager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/Job.php",
        "line": 81,
        "function": "run",
        "class": "OCA\\Collectives\\BackgroundJob\\ExpirePageVersions",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 103,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 93,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/cron.php",
        "line": 152,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/User/User.php",
    "Line": 105,
    "message": "Error while running background job (class: OCA\\Collectives\\BackgroundJob\\ExpirePageVersions, arguments: )",
    "exception": {},
    "CustomMessage": "Error while running background job (class: OCA\\Collectives\\BackgroundJob\\ExpirePageVersions, arguments: )"
  }
}
```

**Comment by solracsf** [comment]
Also affects 25.0.10.

**Comment by theroch** [comment]
Same on Nextcloud 26.0.5 with Collectives 2.7.0
```
TypeError: OC\User\User::__construct(): Argument #3 ($dispatcher) must be of type Symfony\Component\EventDispatcher\EventDispatcherInterface, OC\EventDispatcher\EventDispatcher given, called in apps/collectives/lib/Versions/CollectiveVersionsExpireManager.php on line 121 and defined in lib/private/User/User.php:101
Stack trace:
#0 apps/collectives/lib/Versions/CollectiveVersionsExpireManager.php(121): OC\User\User->__construct()
#1 apps/collectives/lib/Versions/CollectiveVersionsExpireManager.php(96): OCA\Collectives\Versions\CollectiveVersionsExpireManager->expireFolder()
#2 apps/collectives/lib/BackgroundJob/ExpirePageVersions.php(35): OCA\Collectives\Versions\CollectiveVersionsExpireManager->expireAll()
#3 lib/public/BackgroundJob/Job.php(78): OCA\Collectives\BackgroundJob\ExpirePageVersions->run()
#4 lib/public/BackgroundJob/TimedJob.php(103): OCP\BackgroundJob\Job->start()
#5 lib/public/BackgroundJob/TimedJob.php(93): OCP\BackgroundJob\TimedJob->start()
#6 cron.php(152): OCP\BackgroundJob\TimedJob->execute()
#7 {main}
```

**Comment by juliushaertl** [comment]
Feel free to already give the patch in https://github.com/nextcloud/collectives/pull/833 a try

**Comment by theroch** [comment]
I've installed the patch. Is it possible to trigger this event manual or have I to wait for the cron job?

**Comment by theroch** [comment]
I've running the patch now several days without any issues. The message disappeared in our logs.

**Comment by t-aus-m** [comment]
We are running Collectives 2.8.2 on Nextcloud 27.1.2 and unfortunately the issue still persists for us.
